### ISSUE TITLE
Merge service crate into vault

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc-clients#411]
It is only ever consumed by the Vault binary so it doesn't make sense to keep separate. Also if / when we merge this we can combine the `Error` types for some simplification (discussed [here](https://github.com/interlay/interbtc-clients/pull/394#issuecomment-1307235403)).

Possibly related: https://github.com/interlay/interbtc-clients/issues/407

**Comment by nakul1010** [comment]
@gregdhill The service crate is not only used in the `vault` but also used in `faucet` crate. Hence do u recommend it to move it in runtime or keep the crate separate itself?

**Comment by gregdhill** [comment]
@nakul1010 the `faucet` crate only uses a few of the helpers (`on_shutdown` and `wait_or_shutdown`) let's duplicate those for now and see if we can optimize afterward.
