### ISSUE TITLE
Notify Kusama of our supported xcm version

### ISSUE THREAD

**Issue by sander2** [interlay/interbtc-clients#415]
Kusama doesn't that Kintsugi supports xcm v2, so it converts all messages to xcm v1 before sending it It just happens that xcm v1 doesn't support the WeightLimit::Unlimited item, causing some messages to fail.

The Kusama chain did send kintsugi a subscription request to keep it updated of our latest supported XCM version. However, for some reason we didn't process this message (maybe we had an invalid barrier way back when we started the chain). The problem is that the relay chain will only send the request once - as far as it is concerned, there is a subscription now. The solution will be for us to manually add the version subscription - we need to call PolkadotXcm::VersionChangeNotifier::start(...) in a migration.

**Comment by nud3l** [comment]
@sander2  this is fixed now correct?

**Comment by sander2** [comment]
Fixed by the xcm v3 upgrade - it caused a version change notification
