### ISSUE TITLE
Instant seal panic

### ISSUE THREAD

**Issue by sander2** [interlay/interbtc-clients#418]
For the integration tests we used to have feature-gated code duplication to not wait for finalization in the instant-seal integration tests. Since polkadot 0.9.31 finally includes the fix we have been waiting for, we shouldn't require this anymore - we should be able to use finalized events. However, when we switch to the finalized events, there is a problem that occurs only and consistently in `test_automatic_rbf_succeeds`, that gives the error shown below, forcing us to go back to the non-finalizing workaround we were using previously. We should investigate and make an upstream report.

```
Nov 23 11:50:14.364  INFO sc_consensus_manual_seal::rpc: Instant Seal success: CreatedBlock { hash: 0x85a148e068d10319110d4ffdd5fdc6876cf2bf7f3282da63829ddb4f2e21e74c, aux: ImportedAux { header_only: false, clear_justification_requests: false, needs_justification: false, bad_justification: false, is_new_best: true } }    
Nov 23 11:50:14.386  WARN jsonrpsee_core::server::rpc_module: unsubscribe call `author_unwatchExtrinsic` subscription key=SubscriptionKey { conn_id: 0, sub_id: Num(4234576671114396) } not an active subscription
thread 'tokio-runtime-worker' panicked at 'failed to create block: Rpc(ClientError(Call(Custom(ErrorObject { code: ServerError(14000), message: "Consensus Error: Import failed: Potential long-range attack: block not in finalized chain.", data: None }))))', /home/sander/workspace/interlay/polkabtc-clients/runtime/src/rpc.rs:172:14

**Comment by nakul1010** [comment]
I suspect the error was not arising from upstream dependencies but rather from `engine_createBlock` parameters [here](https://github.com/interlay/interbtc-clients/blob/eaf5838959e2c5d01058e85fa5c5e5808fbbbd78/runtime/src/rpc.rs#L172). 
Checkout the Astar readme document [here](https://github.com/AstarNetwork/swanky-node/blob/a0da15772d48035426f2ed241a31d473534a6839/README.md?plain=1#L136).

To verify if this is the problem, the solution would be to test it on the PR #417 branch and update the `engine_createBlock` parameters.
