### ISSUE TITLE
Upgrade the subxt dependency

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc-clients#475]
We are currently using `0.25.0` and the latest version is `0.29.0`.

**Comment by nakul1010** [comment]
Hey @sander2,

[483](https://github.com/interlay/interbtc-clients/pull/483) is the client-side PR, and [nakul/chore_subxt_upgrade](https://github.com/interlay/interbtc/tree/nakul/chore_subxt_upgrade) is the node-side branch. Compiling the client will result in linker errors. I have a question: If I update the `patches` on the client side to point `sp_*` and `cumulus_*` dependencies to `master` instead of the `polkadot-v0.9.40` release (since the subxt substrate version is pointing to the latest releases), will updating the patch only on the client side work, or does the patch need to be updated in both the node and client repositories?

**Comment by nakul1010** [comment]
Furthermore, the error occurs in `Oracle`, `vault` and `faucet` crates because of importing the `runtime` crate in dependency.

**Comment by sander2** [comment]
If I undo the changes to the `sp-core` dependency in `runner/Cargo.toml` and `bitcoin/Cargo.toml` (and do a `cargo update`), the runtime crate compiles just fine. I tested the compilation with `cargo check -p runtime --features parachain-metadata-kintsugi`. Does that solve your problem?

**Comment by nakul1010** [comment]
> If I undo the changes to the `sp-core` dependency in `runner/Cargo.toml` and `bitcoin/Cargo.toml` (and do a `cargo update`), the runtime crate compiles just fine. I tested the compilation with `cargo check -p runtime --features parachain-metadata-kintsugi`. Does that solve your problem?

the checks command is passing in the CI it gives out a linker error while building
 `cargo build -p runtime --features parachain-metadata-kintsugi`

**Comment by nakul1010** [comment]
The runtime package itself is building, but if we add it as a dependency in other crates it will fail. Therefore Oracle, vault and faucet are passing out linker errors. I am trying the solution of updating the substrate dependency patches on the node and client to point to the `master`

**Comment by sander2** [comment]
I can reproduce indeed, this is (one of the) error:
```
untime-6acfcb1b0924b698.wasmtime_runtime.2ee57757-cgu.13.rcgu.o): in function `resolve_vmctx_memory':
          /home/sander/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-runtime-8.0.1/src/debug_builtins.rs:10: multiple definition of `resolve_vmctx_memory'; /home/sander/workspace/interlay/polkabtc-clients/target/debug/deps/libwasmtime_runtime-5e3af6ac359f3784.rlib(wasmtime_runtime-5e3af6ac359f3784.wasmtime_runtime.1c593216-cgu.2.rcgu.o):/home/sander/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-runtime-6.0.2/src/debug_builtins.rs:10: first defined here
```
The dependency is getting included through both the parachain dependency and the subxt, and patching doesn't seem to work for some reason.

> I am trying the solution of updating the substrate dependency patches on the node and client to point to the master

Subxt is not just using master branch on git, it's using the published version on crates.io.. I'm not sure we can do the same on the parachain side (they didn't use to publish all crates on crates.io, but maybe that has changed in the meantime)
