### ISSUE TITLE
Remove embedded node and parachain dependencies

### ISSUE THREAD

**Issue by gregdhill** [interlay/interbtc-clients#486]
**Is your feature request related to a problem? Please describe.**
There are dependencies on our parachain crates including the runtime which can cause upgrade issues since subxt can have conflicting sub-dependencies.

**Describe the solution you'd like**
Remove the embedded node (`runtime/client`) and instead use a local node with `instant-seal`. We already do this for `bitcoind` and `electrs` (see `docker-compose.yml`). This is also the testing strategy adopted by `subxt` so there should be examples upstream for how to do this. Remove any other parachain dependencies and re-declare types if necessary. The only necessary import is probably the Bitcoin parsing for which we can minimize the dependencies upstream.

**Describe alternatives you've considered**
The current alternative is to run an embedded node which is adds substantial compilation time since we also need to build the parachain runtime code.

**Comment by nakul1010** [comment]
The issue has been split into two separate issues: #498 and #497. This way, opening a big PR is not necessary, and individual PRs can close the two mentioned issues
