### ISSUE TITLE
Dependencies version conflicts for latest commit of client and node repo.  

### ISSUE THREAD

**Issue by nakul1010** [interlay/interbtc-clients#489]
**Is your feature request related to a problem? Please describe.**
Currently, the client substrate dependencies are dependent on `polkadot-v0.9.40` version while the para chain is upgraded to `polkadot-v0.9.42` version. Hence both the master version of the repo is not compatible with each other. 

**Describe the solution you'd like**
This needs to be discussed.  

**Describe alternatives you've considered**
Tried patching up client dependencies to `polkadot-v0.9.42`. And adding the master branch as a dependency on the client side.  Checked the cargo tree for the `frame-support` dependency the commit id is different for both, hence the following error is passed out

```
error[E0432]: unresolved imports `frame_support::traits::tokens::Fortitude`, `frame_support::traits::tokens::Preservation`
    --> /home/runner/.cargo/git/checkouts/interbtc-8cf6a8e06590b22b/66dae6a/crates/loans/src/lib.rs:38:38
     |
  38 |         tokens::{fungibles::Inspect, Fortitude, Preservation},
     |                                      ^^^^^^^^^  ^^^^^^^^^^^^ no `Preservation` in `traits::tokens`
     |                                      |
     |                                      no `Fortitude` in `traits::tokens`

```

**Additional context**
This will cause issues if the developer is working on both repos simultaneously. For para chain dependency on the client side, the developer might need to be dependent on the last release version and not the master branch.

**Comment by gregdhill** [comment]
I'm hoping https://github.com/interlay/interbtc-clients/issues/486 will reduce the need for us to align the dependencies in the future but for now the process is to match those for the parachain release. If decide to include a fix for an older version of the clients we should hotfix.
